### PR TITLE
Committing Test2.java

### PR DESCRIPTION
**Pull request by ray3test92101**
Hi 

I have committed Test2.

Please review,
ray3test92101

### CODE REVIEW

**Comment by ray3test92101** [comment]
Hi ray3test92101,

Please make a change to Test 2.  

1. Copy the main method in Test 1.
2. Add a condition for if else "no"
3. Add a condition for else.

Muito Obrigado,
ray2test92101

**Comment by ray3test92101** [comment]
> 
opps

**Comment by ray2test92101** [comment]
Hi ray3test92101,

Please make a change to Test 2.

Copy the main method in Test 1.
Add a condition for if else "no"
Add a condition for else.
Muito Obrigado,
ray2test92101

**Comment by ray3test92101** [comment]
Hi ray2test92101.
I made changes to Test 2 as per your comments.
please approve.
Regards,
ray3test92101

**Comment by ray2test92101** [comment]
Thanks ray3test92101
Approved for Merge pull request 
Regards,
ray2test92101

**Pull request merged**
